version: '3.9'

services:

  httpmonitor:
    container_name: httpmonitor
    image: httpmonitor
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    command:
      - python3
      - -u
      - httpmonitor/manage.py
      - runserver
      - 0.0.0.0:8000
    ports:
      - 4215:8000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://0.0.0.0:8000/"]
      interval: 60s
      timeout: 10s
      retries: 3
    networks:
      - services

  monitor:
    container_name: monitor
    image: httpmonitor
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    command:
      - python3
      - -u
      - monitor/worker.py
    networks:
      - services

networks:
  services:
    name: services
    external: true