version: '3.7'

services:

  httpmonitor:
    container_name: httpmonitor
    image: httpmonitor
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    command:
      - python3
      - -u
      - httpmonitor/manage.py
      - runserver
      - 0.0.0.0:8000
    ports:
      - 4215:8000
    networks:
      - nginx

  monitor:
    container_name: monitor
    image: httpmonitor
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    command:
      - python3
      - -u
      - monitor/worker.py
    networks:
      - nginx

networks:
  nginx:
    name: nginx
    external: true