version: '3.9'

services:

  httpmonitor:
    container_name: httpmonitor
    image: httpmonitor
    build:
      context: ./httpmonitor
      dockerfile: Dockerfile
    env_file:
      - .env
    command:
      - python3
      - -u
      - runserver 0.0.0.0:8000
    ports:
      - 4215:8000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 60s
      timeout: 10s
      retries: 3

  monitor:
    container_name: monitor
    image: monitor
    build:
      context: ./monitor
      dockerfile: Dockerfile
    env_file:
      - .env
    command:
      - python3
      - -u
      - worker.py