# Generated by Django 4.1.4 on 2023-01-26 14:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=300, verbose_name='URL')),
                ('threshold', models.BigIntegerField(verbose_name='Number of errors to tolerate')),
                ('interval', models.BigIntegerField(default=5, verbose_name='Interval for requests in minutes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_code', models.BigIntegerField(verbose_name='Result status code')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.address')),
            ],
        ),
    ]
